name: Angular Build

on:
  push:
    branches: [ main ]
  # optional: also build for PRs targeting main
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'            # caches node_modules automatically

      - name: Install dependencies
        run: npm ci

      # If your project doesn't have a build script yet, add "build": "ng build --configuration=production" to package.json
      - name: Build Angular app
        run: npm run build --if-present

      # If you prefer a direct CLI call, uncomment this and remove the line above:
      # - name: Build Angular app (CLI)
      #   run: npx @angular/cli@latest build --configuration=production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/fulfillment-dashboard/**/*
